---

- name: copy prometheus 1st part config
  template:
    src: "etc/prometheus/alertmanager/alertmanager.yml.j2"
    dest: "{{ prometheus_alertmanager_config_dir }}/conf.d/1-global.yml"
    owner: "{{ prometheus_alertmanager_user }}"
    group: "{{ prometheus_alertmanager_group }}"
    mode: 0644

- name: copy another config parts
  copy:
    src: "{{ item }}"
    dest: "{{ prometheus_alertmanager_config_dir }}/conf.d/"
    owner: "{{ prometheus_alertmanager_user }}"
    group: "{{ prometheus_alertmanager_group }}"
    mode: 0644
  with_fileglob:
    - "{{ playbook_dir }}/files/alertmanager_config_parts/*"

- name: create main config from parts
  assemble:
    src: "{{ prometheus_alertmanager_config_dir }}/conf.d"
    dest: "{{ prometheus_alertmanager_config_dir }}/alertmanager.yml"
    remote_src: true
    owner: "{{ prometheus_alertmanager_user }}"
    group: "{{ prometheus_alertmanager_group }}"
    mode: 0644
  notify:
    - reload alertmanager

- name: copy templates files from playbook directory
  copy:
    src: "{{ playbook_dir }}/files/templates/{{ item }}"
    dest: "{{ prometheus_alertmanager_templates_dir }}/{{ item }}"
    owner: "{{ prometheus_alertmanager_user }}"
    group: "{{ prometheus_alertmanager_group }}"
    mode: 0644
  with_items:
    - "{{ prometheus_alertmanager_templates_files }}"
  notify:
    - reload alertmanager
